### ISSUE TITLE
Report Outline, Presentation and Deadline

### ISSUE THREAD

**Issue by mbarbera** [sacdallago/dataminer#11]
I attach here the link for the online word file, once you open the link click "edit document" and then "edit in the browser" to access the edit version. The report is due on **14th of November by 11.59 pm.** Remember that the presentation is scheduled either on the **26th of October or on the 2nd of November**. 

FYI: The exam is scheduled on the **22nd of November from 1:30 PM to 4:30 PM**

Here is the link:

https://entuedu-my.sharepoint.com/personal/n1609543k_e_ntu_edu_sg/_layouts/15/guestaccess.aspx?guestaccesstoken=AF%2bCKVMi0XPAZKFFALxlPfC8Xr1K%2fXu%2bXzUJgWpoNLo%3d&docid=1606d5db4fcee48eba2ee2e630a605228&rev=1

**Comment by mbarbera** [comment]
Last version of the Report, GitHub Repo cited

[Group14_Report.pdf](https://github.com/sacdallago/dataminer/files/589062/Group14_Report.pdf)

**Comment by sacdallago** [comment]
I'd say: done :)
